let notes = [
  {
    id: 1,
    img: '',
    name: `Shoping List 1`,
    creationDate: '2021-11-20',
    category: 'Task',
    content: 'Tomatoes, bread',
    dates: '3/5/2021',
    archived: false,
  },
  {
    id: 2,
    img: '',
    name: 'Shoping List 2',
    creationDate: '2021-02-10',
    category: 'Task',
    content: 'Phone, Tv 3/5/2021',
    dates: '3/5/2021',
    archived: false,
  },
  {
    id: 3,
    img: '',
    name: 'Shoping List 3',
    creationDate: '2021-04-20',
    category: 'Idea',
    content: 'Tomatoes, bread, milk',
    dates: '3/5/2021',
    archived: true,
  },
  {
    id: 4,
    img: '',
    name: 'Shoping List 4',
    creationDate: '2021-04-20',
    category: 'Task',
    content: 'Tomatoes, bread',
    dates: '3/5/2021',
    archived: false,
  },
  {
    id: 5,
    img: '',
    name: 'Shoping List 5',
    creationDate: '2018-12-10',
    category: 'Task',
    content: 'Tomatoes, bread',
    dates: '3/5/2021',
    archived: false,
  },
  {
    id: 6,
    img: '',
    name: 'Some random thought',
    creationDate: '2021-04-20',
    category: 'Random Thought',
    content: 'Tomatoes, bread',
    dates: '3/5/2021',
    archived: true,
  },
];

module.exports = notes;
